[package]
name = "sock_client"
version = "0.1.0"
edition = "2021"

[lib]
name = "sock_client"
crate-type = ["cdylib"]

[dependencies]
socket = { path = "../socket" }
iced = "0.4.2"
iced_native = "0.5.1"