[package]
name = "socket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
concat-arrays = "0.1.2"
tokio = { version = "1.20.0", features = ["macros", "net", "rt-multi-thread", "io-util"] }