[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket = { path = "../socket" }
tokio = { version = "1.20.0", features = ["macros", "net", "rt-multi-thread", "io-util"] }